# Build settings in main config file
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "flmcci"
description: > # this means to ignore newlines until "email:"
   Photography by aaucci

email: a-mail@mail.mail
#blog logo
logo: "/flmcci/assets/images/flmcci_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "https://res.cloudinary.com/dzr37z305/image/upload/v1731110684/000367770007_uxg6pe.jpg"

name: 'Aaron Bantay'
author: 'Aaron Bantay'
author_image: ''

paginate:	5

url: "http://abant006.github.io" # the base hostname & protocol for your site
baseurl: "/flmcci"
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: github
    url: https://github.com/abant006
    desc: ""
    share_url: ""
    share_title: ""
    share_link: ""

  - icon: instagram
    url: https://www.instagram.com/flmcci/
    desc: Follow me on instagram
    share_url: ""
    share_title: ""
    share_link: ""

# jekyll-tagging. Defines the layout used to generate tag pages
# this will look for _layouts/tag_page.html and use it to generate tag pages into the _site/tag directory
tag_page_layout: tag_page
tag_page_dir: tag
